# Generated by Django 4.2.2 on 2023-10-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopByNewCollection',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='ShopByNewCollection/images')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Customer_Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Actual_Cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Quantity', models.PositiveIntegerField(default=1, null=True)),
                ('Stock_Of_Product_Quantity', models.PositiveIntegerField(default=0, null=True)),
                ('Stock_Of_Product_Sizes_Available', models.TextField(max_length=1000, null=True)),
                ('Ships_in_Days', models.PositiveIntegerField(default=10)),
                ('Product_Description', models.TextField(max_length=2800)),
                ('Measurement_Details', models.TextField(max_length=2000)),
                ('Fabric_Used', models.TextField(max_length=1500)),
                ('Care_Instructions', models.TextField(max_length=1500)),
                ('Size_Of_Product', models.ManyToManyField(to='ShopByNewCollection.size')),
            ],
        ),
    ]
