# Generated by Django 4.2.2 on 2023-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopByNewCollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbynewcollection',
            name='Size_Of_Product',
        ),
        migrations.AddField(
            model_name='shopbynewcollection',
            name='Size_Of_Product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
