# Generated by Django 4.2.2 on 2023-10-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Product_Image',
            new_name='Image',
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('Product_Name', models.CharField(max_length=150)),
                ('Product_Image', models.ImageField(null=True, upload_to='store/images')),
                ('Product_Small_Desc', models.CharField(max_length=250)),
                ('Product_Quantity', models.PositiveIntegerField(default=0)),
                ('Product_Desc', models.TextField(max_length=2000)),
                ('Original_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Selling_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False, help_text='0=default , 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default , 1=Trending')),
                ('tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keyword', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
