# Generated by Django 4.2.2 on 2023-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('1', 'Size 1'), ('2', 'Size 2'), ('3', 'Size 3'), ('4', 'Size 4')], default='', max_length=3),
        ),
    ]
