# Generated by Django 4.2.2 on 2023-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
