# Generated by Django 4.2.2 on 2023-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_products_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('cod_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
